name: geodetect
description: "Human count detection application."

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Maps
  google_maps_flutter: ^2.9.0

  # Localization
  easy_localization: ^3.0.7

  # Image
  image_picker: ^1.1.2

  # Location
  geolocator: ^13.0.2

  # State Management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  # Storage
  path_provider: ^2.1.5

  # Animation
  lottie: ^3.1.3

  # Network
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/
